site_name: quick-menu
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - navigation.footer
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
watch:
  - src/quick_menu

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - offline
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - footnotes
copyright: |
  &copy; 2023, Stephan Poole
